init:
- cmd: >-
    tzutil /s "Eastern Standard Time"
image: Visual Studio 2017

nuget:
  disable_publish_on_pr: true
skip_tags: true
build_script:
- cmd: >-
    choco install cake.portable -r -y

    cake
artifacts:
  path: Artifacts\*.nupkg
test: off
notifications:
- provider: Slack
  incoming_webhook: 
    secure: jAHwieC/ls9GRYV3YawixFkHoUekBo17Sq63Ik5AYYKHbm+GZwLKJy9ni7gsxwXVwA+79fbacsARTacf1bvYSJFALusnWuqqBa208OqYvFc=
  channel: builds
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false    
